version: '3'

networks:
  laravel:


services:
  nginx:
    image: library/nginx:stable-alpine
    container_name: nginx-bilgeweb
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8060:80"
    depends_on:
      - php
      - mysql
    networks:
      laravel:
  mysql:
    image: library/mysql:5.7.22
    container_name: mysql-bilgeweb
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3308:3306"

    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER : homestead
      MYSQL_PASSWORD: homestead
      MYSQL_ROOT_PASSWORD: homestead
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      laravel:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-bilgeweb
    volumes:
      - ./:/var/www/html
    ports:
      - "6000:9000"
    networks:
      laravel:
